version: '3.8'

services:
  db:
    image: postgres
    container_name: importer-postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - path: .env
        required: true
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  importer:
    container_name: importer-service
    build: .
    image: importer-service
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - path: .env
        required: true
    environment:
      POSTGRES_HOST: importer-postgres:5432

  